name: Build Apple Unity Plugins

on:
  workflow_dispatch:

jobs:
  build-tgz:
    runs-on: macos-latest
    
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Đã nâng cấp lên Node 24

      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện NPM (Bổ sung)
        run: npm install

      - name: Chạy script build.py
        run: |
          python3 build.py -b Build Pack

      - name: Upload thư mục Build làm Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Apple-Plugins-TGZ
          path: Build/*.tgz
